plugins { id 'com.android.application' }

android {
    namespace 'com.mrkaath2.myfinance'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrkaath2.myfinance'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '6.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.9.0'
}
