(function(){
'use strict';
var MODEL='gpt-4.1-mini',editId=null,activeType='lifeExpense',fuelEditId=null,seq=0,waiters={};

function E(id){return document.getElementById(id)}
function esc10(s){return String(s==null?'':s).replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]})}
function money10(n){return typeof money==='function'?money(n):Math.round(Number(n)||0).toLocaleString('ru-RU')+' ₽'}
function pct10(n){return typeof pct==='function'?pct(n):(Number(n)||0).toLocaleString('ru-RU')+'%'}
function say(t){if(typeof toast==='function')toast(t);else alert(t)}
function getKey(){try{return window.SecureStore&&SecureStore.getSecret?SecureStore.getSecret():''}catch(e){return ''}}
function setKey(v){try{return window.SecureStore&&SecureStore.setSecret?SecureStore.setSecret(v):false}catch(e){return false}}
function clearKey(){try{return window.SecureStore&&SecureStore.clearSecret?SecureStore.clearSecret():false}catch(e){return false}}
function ready(){return !!getKey()}

function compactNav(){
 var nav=document.querySelector('.nav');if(!nav)return;
 ['invest','history','settings'].forEach(function(id){var b=nav.querySelector('[data-go="'+id+'"]');if(b)b.style.display='none'});
 var st=nav.querySelector('[data-go="stats"]');if(st){st.innerHTML='<span class="ico">▥</span>Финансы';st.style.display='block'}
 if(!nav.querySelector('[data-v10-ai]')){var a=document.createElement('button');a.setAttribute('data-v10-ai','1');a.innerHTML='<span class="ico">✦</span>ИИ';a.onclick=function(){go10('ai')};if(st)st.insertAdjacentElement('afterend',a);else nav.appendChild(a)}
 if(!E('v10gear')){var h=document.querySelector('header'),r=E('syncBtn'),g=document.createElement('button');g.className='icon-btn';g.id='v10gear';g.textContent='⚙';g.setAttribute('aria-label','Настройки');if(r)r.insertAdjacentElement('beforebegin',g);else if(h)h.appendChild(g);g.onclick=function(){go10('settings')}}
}
function addStyle(){
 if(E('v10style'))return;
 var s=document.createElement('style');s.id='v10style';
 s.textContent='.nav{grid-template-columns:repeat(4,1fr)!important}.v10modal{position:fixed;inset:0;display:none;align-items:flex-end;justify-content:center;background:rgba(0,0,0,.66);backdrop-filter:blur(10px);padding:12px;z-index:120}.v10modal.show{display:flex}.v10sheet{width:min(780px,100%);max-height:90vh;overflow:auto;background:#101b2d;border:1px solid var(--line);border-radius:24px;padding:16px;box-shadow:var(--shadow)}.v10row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}.v10actions{display:flex;gap:5px;justify-content:flex-end;flex-wrap:wrap;margin-top:5px}.v10actions button{border:1px solid var(--line);background:#182842;color:var(--text);border-radius:10px;padding:6px 8px;font-size:10px;font-weight:800}.v10chat{display:grid;gap:8px;max-height:380px;overflow:auto}.v10msg{padding:12px;border-radius:15px;background:#0d192b;border:1px solid var(--line);line-height:1.45}.v10msg.ai{background:#10243a}.v10dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#fb7185}.v10dot.on{background:#6ee7b7}.v10card{width:100%;text-align:left;color:var(--text);cursor:pointer}.v10detect{padding:12px;border:1px solid var(--line);border-radius:15px;background:#0d192b;margin-top:8px}@media(max-width:430px){.nav button{font-size:9px}.nav .ico{font-size:15px}}';
 document.head.appendChild(s)
}
function finance10(){
 var s=E('stats');if(!s)return;
 s.innerHTML='<div class="section-title" style="margin-top:5px">Финансы</div><div class="hero" style="padding:18px"><div class="eyebrow">Один экран</div><h2 style="font-size:24px">Доходы, расходы, резервы и вклад.</h2><p>Нажми на категорию — увидишь историю, сможешь добавить, изменить или удалить запись.</p></div><div class="section-title">Обзор</div><div class="summary-grid">'+
 '<button class="metric v10card" data-t="income"><div class="k">💰 Доход</div><div class="v" id="xIncome">0 ₽</div><div class="v10mini" id="xIncomeSub">Среднее 0 ₽/день</div></button>'+
 '<button class="metric v10card" data-t="lifeExpense"><div class="k">🛒 Траты на жизнь</div><div class="v danger" id="xLife">0 ₽</div><div class="v10mini" id="xLifeSub">Среднее 0 ₽/день</div></button>'+
 '<button class="metric v10card" data-t="fuel"><div class="k">⛽ Бензин</div><div class="v good" id="xFuel">0 ₽</div><div class="v10mini" id="xFuelSub">Отложено 0 ₽</div></button>'+
 '<button class="metric v10card" data-t="car"><div class="k">🚗 Машина</div><div class="v" id="xCar">0 ₽</div><div class="v10mini">Резерв</div></button>'+
 '<button class="metric v10card" data-t="buffer"><div class="k">🛡️ Финансовый запас</div><div class="v" id="xBuffer">0 ₽</div><div class="v10mini">Подушка</div></button>'+
 '<button class="metric v10card" data-t="deposit"><div class="k">🏦 Вклад</div><div class="v good" id="xDeposit">0 ₽</div><div class="v10mini" id="xDepositSub">Ставка —</div></button>'+
 '<button class="metric v10card" data-t="investment"><div class="k">📈 Инвестиции</div><div class="v good" id="xInvest">0 ₽</div><div class="v10mini">Внесено</div></button>'+
 '<div class="metric"><div class="k">🚗 Рабочий пробег</div><div class="v" id="xKm">0 км</div><div class="v10mini" id="xKmSub">0 дней</div></div></div>'+
 '<div class="section-title">📌 Быстрые действия</div><div class="row"><button class="btn secondary" id="quickExpense" type="button">+ Трата</button><button class="btn secondary" id="quickDeposit" type="button">+ Вклад</button></div><div class="row" style="margin-top:10px"><button class="btn secondary" id="quickCar" type="button">+ Машина</button><button class="btn secondary" id="quickBuffer" type="button">+ Запас</button></div>'+
 '<div class="section-title">🧾 Последние операции</div><div id="xRecent"></div><button class="btn secondary full" id="xAll" style="margin-top:10px" type="button">Вся история</button>';
 s.querySelectorAll('.v10card').forEach(function(b){b.onclick=function(){openType10(b.getAttribute('data-t'))}});
 E('quickExpense').onclick=function(){openType10('lifeExpense')};E('quickDeposit').onclick=function(){openType10('deposit')};E('quickCar').onclick=function(){openType10('car')};E('quickBuffer').onclick=function(){openType10('buffer')};E('xAll').onclick=function(){openType10('all')}
}
async function totals10(){
 var c=await all('calculations'),r=await all('refuels'),l=await all('ledger');
 var income=0,km=0,fuel=0,car=0,buf=0,dep=0,inv=0,life=0,recent=[];
 c.forEach(function(x){var d=x.data||{};income+=Number(d.amount)||0;km+=Number(d.mileage)||0;fuel+=Number(d.fuel)||0;car+=Number(d.car)||0;buf+=Number(d.buffer)||0;dep+=Number(d.deposit)||0;inv+=Number(d.invest)||0;recent.push({source:'day',id:x.id,type:'income',amount:Number(d.amount)||0,sign:1,category:'Яндекс Доставка',note:'Расчёт дня',ts:x.ts})});
 l.forEach(function(x){var a=Number(x.amount)||0,sg=Number(x.sign||1);if(x.type==='income')income+=a*sg;if(x.type==='car')car+=a*sg;if(x.type==='buffer')buf+=a*sg;if(x.type==='deposit')dep+=a*sg;if(x.type==='investment')inv+=a*sg;if(x.type==='lifeExpense')life+=a;recent.push({source:'ledger',id:x.id,type:x.type,amount:a,sign:sg,category:x.category,note:x.note,ts:x.ts})});
 var spent=r.reduce(function(s,x){return s+(Number(x.cost)||0)},0);r.forEach(function(x){recent.push({source:'fuel',id:x.id,type:'fuel',amount:Number(x.cost)||0,sign:-1,category:'Бензин',note:x.note||'Заправка',ts:x.ts})});recent.sort(function(a,b){return b.ts-a.ts});
 var days=Math.max(1,c.length),allSpent=life+spent;return {c:c,r:r,l:l,income:income,km:km,fuel:fuel,car:car,buf:buf,dep:dep,inv:inv,life:life,spent:spent,fuelLeft:Math.max(0,fuel-spent),avgIncome:income/days,avgSpend:allSpent/days,days:days,allSpent:allSpent,recent:recent}
}
function typeLabel10(t){return ({income:'Доход',lifeExpense:'Траты на жизнь',fuel:'Бензин',car:'Машина',buffer:'Финансовый запас',deposit:'Вклад',investment:'Инвестиции'})[t]||'Операция'}
async function refresh10(){
 var t=await totals10(),s=await loadSettings(),set=function(id,v){var e=E(id);if(e)e.textContent=v};
 set('xIncome',money10(t.income));set('xIncomeSub','Среднее '+money10(t.avgIncome)+'/день');set('xLife',money10(t.life));set('xLifeSub','Среднее '+money10(t.life/Math.max(1,t.days))+'/день');set('xFuel',money10(t.fuelLeft));set('xFuelSub','Отложено '+money10(t.fuel)+' · заправки '+money10(t.spent));set('xCar',money10(Math.max(0,t.car)));set('xBuffer',money10(Math.max(0,t.buf)));set('xDeposit',money10(Math.max(0,t.dep)));set('xDepositSub','Ставка '+pct10(Number(s.depositRate)||0)+' · ≈ '+money10(t.dep*(Number(s.depositRate)||0)/100/12)+'/мес');set('xInvest',money10(Math.max(0,t.inv)));set('xKm',t.km.toLocaleString('ru-RU')+' км');set('xKmSub',t.c.length+' дней');
 var arr=t.recent.slice(0,10);E('xRecent').innerHTML=arr.length?arr.map(function(x){var canEdit=x.source!=='day';return '<div class="v10row"><div><div class="date">'+new Date(x.ts).toLocaleString('ru-RU')+'</div><b>'+esc10(typeLabel10(x.type))+'</b><div class="v10mini">'+esc10(x.category||'')+(x.note?' · '+esc10(x.note):'')+'</div></div><div><b>'+((x.sign||1)>0?'+':'−')+money10(x.amount)+'</b><div class="v10actions"><button data-e="'+x.source+'" data-id="'+x.id+'" data-t="'+x.type+'">'+(canEdit?'Изм.':'Открыть')+'</button>'+(canEdit?'<button data-d="'+x.source+'" data-id="'+x.id+'">Удал.</button>':'')+'</div></div></div>'}).join(''):'<div class="card empty">Операций пока нет.</div>';
 E('xRecent').querySelectorAll('[data-e]').forEach(function(b){b.onclick=function(){editAny10(b.getAttribute('data-e'),Number(b.getAttribute('data-id')),b.getAttribute('data-t'))}});
 E('xRecent').querySelectorAll('[data-d]').forEach(function(b){b.onclick=function(){deleteAny10(b.getAttribute('data-d'),Number(b.getAttribute('data-id')))}})
}
function addOpModal10(){
 if(E('v10Op'))return;
 document.body.insertAdjacentHTML('beforeend','<div class="v10modal" id="v10Op"><div class="v10sheet"><div class="row"><div><div class="eyebrow" id="opEye">Операция</div><h2 id="opTitle" style="margin:5px 0 0;font-size:22px">Добавить</h2></div><button class="icon-btn" id="opClose" type="button">×</button></div><div class="grid" style="margin-top:14px"><div><label>Тип</label><select id="opType"><option value="income">💰 Доход</option><option value="lifeExpense">🛒 Трата на жизнь</option><option value="deposit">🏦 Вклад</option><option value="investment">📈 Инвестиции</option><option value="car">🚗 Машина</option><option value="buffer">🛡️ Финансовый запас</option></select></div><div><label>Сумма, ₽</label><input id="opAmount" type="number" inputmode="decimal"></div><div><label>Действие</label><select id="opSign"><option value="1">Добавить</option><option value="-1">Уменьшить / списать</option></select></div><div id="opCatBox"><label>Категория</label><input id="opCat" placeholder="Например, продукты"></div><div><label>Комментарий</label><input id="opNote" placeholder="Например, супермаркет"></div><div><label>Дата</label><input id="opDate" type="date"></div></div><div class="row" style="margin-top:12px"><button class="btn secondary" id="opCancel" type="button">Отмена</button><button class="btn" id="opSave" type="button">Сохранить</button></div><div class="section-title">История категории</div><div id="opHistory"></div></div></div>');
 E('opClose').onclick=closeOp10;E('opCancel').onclick=closeOp10;E('opSave').onclick=saveOp10;E('opType').onchange=function(){activeType=this.value;renderOpHistory10(activeType)}
}
function closeOp10(){E('v10Op').classList.remove('show');editId=null}
async function openType10(type,id){
 if(type==='fuel'){openFuel10(id);return}activeType=type;editId=id||null;E('opType').value=type==='all'?'lifeExpense':type;E('opTitle').textContent=id?'Изменить: '+typeLabel10(type):(type==='all'?'Вся история':'Добавить: '+typeLabel10(type));E('opEye').textContent=type==='all'?'Финансы':typeLabel10(type);E('opAmount').value='';E('opCat').value='';E('opNote').value='';E('opDate').value=new Date().toISOString().slice(0,10);E('opSign').value=type==='lifeExpense'?'-1':'1';E('opCatBox').style.display=type==='lifeExpense'||type==='income'?'block':'none';if(id){var e=(await all('ledger')).find(function(x){return x.id===id});if(e){E('opAmount').value=e.amount;E('opCat').value=e.category||'';E('opNote').value=e.note||'';E('opDate').value=new Date(e.ts).toISOString().slice(0,10);E('opSign').value=String(e.sign||1)}}E('v10Op').classList.add('show');await renderOpHistory10(type)}
async function renderOpHistory10(type){var t=await totals10(),rows=type==='all'?t.recent:(await all('ledger')).filter(function(x){return x.type===type}).sort(function(a,b){return b.ts-a.ts});if(!rows.length){E('opHistory').innerHTML='<div class="empty">Записей пока нет.</div>';return}E('opHistory').innerHTML=rows.map(function(x){var src=x.source||'ledger';return '<div class="v10row"><div><div class="date">'+new Date(x.ts).toLocaleString('ru-RU')+'</div><b>'+esc10(typeLabel10(x.type))+'</b><div class="v10mini">'+esc10(x.category||'')+' '+esc10(x.note||'')+'</div></div><div><b>'+((x.sign||1)>0?'+':'−')+money10(x.amount)+'</b><div class="v10actions">'+(src==='fuel'?'<button data-fe="'+x.id+'">Изм.</button><button data-fd="'+x.id+'">Удал.</button>':'<button data-oe="'+x.id+'" data-ot="'+x.type+'">Изм.</button><button data-od="'+x.id+'">Удал.</button>')+'</div></div></div>'}).join('');E('opHistory').querySelectorAll('[data-oe]').forEach(function(b){b.onclick=function(){openType10(b.getAttribute('data-ot'),Number(b.getAttribute('data-oe')))}});E('opHistory').querySelectorAll('[data-od]').forEach(function(b){b.onclick=function(){deleteAny10('ledger',Number(b.getAttribute('data-od')))}});E('opHistory').querySelectorAll('[data-fe]').forEach(function(b){b.onclick=function(){openFuel10(Number(b.getAttribute('data-fe')))}});E('opHistory').querySelectorAll('[data-fd]').forEach(function(b){b.onclick=function(){deleteAny10('fuel',Number(b.getAttribute('data-fd')))}})}
async function saveOp10(){var type=E('opType').value,amount=Math.abs(Number(E('opAmount').value)||0);if(!amount){say('Укажи сумму');return}var d=E('opDate').value,ts=d?new Date(d+'T12:00:00').getTime():Date.now(),data={type:type,amount:amount,sign:type==='lifeExpense'?-1:Number(E('opSign').value)||1,category:E('opCat').value.trim(),note:E('opNote').value.trim(),ts:ts};if(editId)data.id=editId;await put('ledger',data);closeOp10();await refresh10();say('Операция сохранена')}
async function deleteAny10(source,id){if(source==='fuel')await deleteFuel10(id);else if(source==='day'){say('Дневной расчёт редактируется во вкладке Доход.');return}else{await new Promise(function(res,rej){var tr=db.transaction('ledger','readwrite'),q=tr.objectStore('ledger').delete(id);q.onsuccess=res;q.onerror=function(){rej(q.error)}});await refresh10();say('Операция удалена')}}
function editAny10(source,id,type){if(source==='fuel')openFuel10(id);else if(source==='day')go10('calc');else openType10(type,id)}
async function openFuel10(id){fuelEditId=id||null;E('fuelModal').classList.add('show');E('refuelLiters').value='';E('refuelCost').value='';E('refuelPriceHint').textContent='Цена за литр посчитается автоматически.';if(id){var r=(await all('refuels')).find(function(x){return x.id===id});if(r){E('refuelLiters').value=r.liters;E('refuelCost').value=r.cost}}}
async function saveFuel10(){var l=Math.abs(Number(E('refuelLiters').value)||0),c=Math.abs(Number(E('refuelCost').value)||0);if(!l||!c){say('Укажи литры и сумму');return}var d={ts:Date.now(),liters:l,cost:c,pricePerLiter:c/l};if(fuelEditId)d.id=fuelEditId;await put('refuels',d);fuelEditId=null;E('fuelModal').classList.remove('show');await refresh10();say('Заправка сохранена')}
async function deleteFuel10(id){await new Promise(function(res,rej){var tr=db.transaction('refuels','readwrite'),q=tr.objectStore('refuels').delete(id);q.onsuccess=res;q.onerror=function(){rej(q.error)}});await refresh10();say('Заправка удалена')}

function addAi10(){
 if(E('ai'))return;var main=document.querySelector('main'),st=E('stats');if(!main||!st)return;var s=document.createElement('section');s.id='ai';s.className='view';
 s.innerHTML='<div class="section-title" style="margin-top:5px">ИИ</div><div class="hero" style="padding:18px"><div class="eyebrow">Настоящий AI</div><h2 style="font-size:24px">Спроси про свои деньги.</h2><p>Настоящий ИИ анализирует твою историю и может посмотреть скриншоты Яндекс Доставки, банка и чеков.</p><div style="margin-top:10px"><span class="v10dot" id="aiDot"></span> <b id="aiStatus">ИИ не подключён</b></div><button class="btn full" id="aiSetupBtn" style="margin-top:12px" type="button">Подключить ИИ</button></div><div class="section-title">📸 Скриншот</div><div class="card"><label class="btn full" for="aiImage">Выбрать скриншот</label><input id="aiImage" type="file" accept="image/*" style="display:none"><div class="note" id="aiImgStatus" style="display:none;margin-top:10px"></div><div id="aiDetected"></div></div><div class="section-title">💬 Чат</div><div class="card"><div id="aiChat" class="v10chat"></div><div class="row" style="margin-top:10px;grid-template-columns:1fr auto"><input id="aiQuestion" placeholder="Например: какой средний расход в день?"><button class="btn" id="aiAsk" type="button">Спросить</button></div></div>';main.insertBefore(s,st)
}
function addAiModal10(){
 if(E('aiSettings'))return;document.body.insertAdjacentHTML('beforeend','<div class="v10modal" id="aiSettings"><div class="v10sheet"><div class="row"><div><div class="eyebrow">Подключение</div><h2 style="margin:5px 0 0;font-size:22px">Настоящий ИИ</h2></div><button class="icon-btn" id="aiClose" type="button">×</button></div><div class="card" style="margin-top:14px"><label>OpenAI API key</label><input id="apiKey" type="password" autocomplete="off" placeholder="Вставь ключ"><div class="hint">Ключ хранится локально через Android Keystore. Не добавляй его в GitHub.</div><div class="v10mini" style="margin-top:8px">Модель: '+MODEL+'</div></div><div class="row" style="margin-top:12px"><button class="btn secondary" id="aiClear" type="button">Удалить ключ</button><button class="btn" id="aiSave" type="button">Сохранить и проверить</button></div><div class="note" style="margin-top:10px">API OpenAI оплачивается отдельно от подписки ChatGPT.</div></div></div>');
 E('apiKey').value=getKey();E('aiClose').onclick=function(){hideAiSetup()};E('aiClear').onclick=function(){clearKey();E('apiKey').value='';statusAi()};E('aiSave').onclick=async function(){var k=E('apiKey').value.trim();if(!k){say('Вставь API key');return}if(!setKey(k)){say('Не удалось сохранить ключ');return}var z=extract(await aiCall('Ответь одним словом: ОК',''));if(z){hideAiSetup();statusAi();say('ИИ подключён')}else say('Проверка ИИ не прошла')}
}
function hideAiSetup(){E('aiSettings').classList.remove('show')}
function statusAi(){var on=ready();if(E('aiDot'))E('aiDot').classList.toggle('on',on);if(E('aiStatus'))E('aiStatus').textContent=on?'ИИ подключён':'ИИ не подключён'}
function extract(raw){try{var j=JSON.parse(raw);if(j.output_text)return j.output_text;var a=j.output||[],p=[];a.forEach(function(o){(o.content||[]).forEach(function(c){if(c.text)p.push(c.text)})});return p.join('\\n')}catch(e){return String(raw||'')}}
function aiCall(prompt,image){return new Promise(function(resolve){if(!ready()){say('Сначала подключи ИИ');resolve('');return}var id='v'+(++seq);waiters[id]=resolve;try{OpenAINative.request(JSON.stringify({id:id,prompt:prompt,image:image||''}))}catch(e){delete waiters[id];say('ИИ недоступен');resolve('')}})}
window.onOpenAIResult=function(id,text){if(waiters[id]){var r=waiters[id];delete waiters[id];r(text)}};window.onOpenAIError=function(id,text){if(waiters[id]){var r=waiters[id];delete waiters[id];say(text||'Ошибка ИИ');r('')}};

async function chatAdd(role,text){await put('aiChat',{ts:Date.now(),role:role,text:text});await renderChat10()}
async function renderChat10(){var a=(await all('aiChat')).sort(function(x,y){return x.ts-y.ts}),e=E('aiChat');if(!e)return;e.innerHTML=a.length?a.map(function(x){return '<div class="v10msg '+(x.role==='ai'?'ai':'')+'"><div class="v10mini">'+(x.role==='ai'?'ИИ':'Ты')+'</div><div>'+esc10(x.text)+'</div></div>'}).join(''):'<div class="empty">Напиши вопрос — например: «какой средний расход в день?»</div>';e.scrollTop=e.scrollHeight}
async function askAI(){var q=E('aiQuestion').value.trim();if(!q)return;E('aiQuestion').value='';await chatAdd('user',q);E('aiAsk').disabled=true;try{var t=await totals10(),p='Ты личный финансовый помощник пользователя в РФ. Отвечай по-русски, конкретно и без выдумывания цифр. Данные приложения: '+JSON.stringify({income:t.income,avgIncome:t.avgIncome,avgSpend:t.avgSpend,lifeExpenses:t.life,fuelReserved:t.fuel,fuelSpent:t.spent,fuelLeft:t.fuelLeft,carReserve:t.car,buffer:t.buf,deposit:t.dep,investments:t.inv,km:t.km,days:t.c.length,recent:t.recent.slice(0,20)})+' Вопрос: '+q;var ans=extract(await aiCall(p,''));await chatAdd('ai',ans||'Не удалось получить ответ.')}finally{E('aiAsk').disabled=false}}
async function compress10(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onerror=reject;r.onload=function(){var im=new Image();im.onerror=reject;im.onload=function(){var max=1400,w=im.width,h=im.height;if(Math.max(w,h)>max){var k=max/Math.max(w,h);w=Math.round(w*k);h=Math.round(h*k)}var c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',.72))};im.src=r.result};r.readAsDataURL(file)})}
function parseJson10(text){var t=String(text||'').trim(),a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<=a)return null;try{return JSON.parse(t.slice(a,b+1))}catch(e){return null}}
async function analyze10(file){if(!ready()){say('Сначала подключи ИИ');return}var st=E('aiImgStatus');st.style.display='block';st.textContent='ИИ смотрит скриншот…';try{var img=await compress10(file),prompt='Проанализируй этот финансовый скриншот. Верни ТОЛЬКО JSON с полями summary и operations. Формат: {"summary":"кратко","operations":[{"type":"income|lifeExpense|fuel|deposit|investment|car|buffer","amount":0,"liters":null,"category":"...","note":"...","date":"YYYY-MM-DD или null"}]}. Учитывай только реальные операции. Не считай баланс, количество заказов, проценты и справочные цифры операциями. Для Яндекс Доставки найди фактический заработок. Для чека или банка — фактическую трату. Для заправки — сумму и литры, если видны. Сомнительные значения пропусти.';var obj=parseJson10(extract(await aiCall(prompt,img)));if(!obj){st.textContent='ИИ ответил, но результат не удалось разобрать.';return}st.textContent=obj.summary||'Проверь найденные операции.';showDetected10(obj.operations||[])}catch(e){st.textContent='Не удалось обработать скриншот. Проверь API key и интернет.'}}
function showDetected10(ops){var e=E('aiDetected');if(!ops.length){e.innerHTML='<div class="note" style="margin-top:10px">Операций не найдено.</div>';return}e.innerHTML='<div class="section-title">Проверь найденное</div>'+ops.map(function(x){return '<div class="v10detect"><div style="display:flex;justify-content:space-between;gap:8px"><b>'+esc10(typeLabel10(x.type))+'</b><b>'+money10(x.amount)+'</b></div><div class="v10mini">'+esc10(x.category||'')+(x.liters?' · '+x.liters+' л':'')+(x.date?' · '+x.date:'')+'</div><div class="v10mini">'+esc10(x.note||'')+'</div></div>'}).join('')+'<button class="btn full" id="aiAddFound" style="margin-top:10px" type="button">Добавить в историю</button>';E('aiAddFound').onclick=async function(){for(var i=0;i<ops.length;i++){var x=ops[i],ts=x.date?new Date(x.date+'T12:00:00').getTime():Date.now();if(x.type==='fuel')await put('refuels',{ts:ts,liters:Number(x.liters)||0,cost:Number(x.amount)||0,pricePerLiter:x.liters?(Number(x.amount)||0)/(Number(x.liters)||1):0,note:x.note||'ИИ'});else await put('ledger',{type:x.type,amount:Math.abs(Number(x.amount)||0),sign:x.type==='lifeExpense'?-1:1,category:x.category||typeLabel10(x.type),note:x.note||'ИИ: скриншот',ts:ts})}await refresh10();say('Операции добавлены')}}
function patchSettings(){var s=E('settings');if(s&&!E('settingsBack10')){var b=document.createElement('button');b.id='settingsBack10';b.className='btn secondary full';b.textContent='← Назад';b.onclick=function(){showView('home')};s.insertBefore(b,s.firstChild)}}
document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('#aiSetupBtn'):null;if(!b)return;var m=E('aiSettings');if(m){m.classList.add('show');var k=E('apiKey');if(k)k.value=getKey()}});document.addEventListener('pointerup',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('#aiSetupBtn'):null;if(b&&E('aiSettings')){E('aiSettings').classList.add('show');var k=E('apiKey');if(k)k.value=getKey()}});
function go10(id){showView(id);if(id==='stats')refresh10();if(id==='ai'){statusAi();renderChat10()}}
async function clearAll10(){try{var tr=db.transaction(['calculations','refuels','ledger','aiChat'],'readwrite');tr.objectStore('calculations').clear();tr.objectStore('refuels').clear();tr.objectStore('ledger').clear();tr.objectStore('aiChat').clear();await new Promise(function(r){tr.oncomplete=r;tr.onerror=r})}catch(e){}await refresh10();await renderChat10();say('Вся история очищена')}
async function init10(){
 compactNav();addStyle();finance10();addAi10();addAiModal10();addOpModal10();patchSettings();await refresh10();await renderChat10();statusAi();
 var setup=E('aiSetupBtn');if(setup)setup.onclick=function(){E('aiSettings').classList.add('show');E('apiKey').value=getKey();};
 document.querySelectorAll('.nav button').forEach(function(b){var id=b.getAttribute('data-go');if(id==='home'||id==='calc')b.onclick=function(){showView(id)};if(id==='stats')b.onclick=function(){go10('stats')};if(b.hasAttribute('data-v10-ai'))b.onclick=function(){go10('ai')}});
 var sb=E('saveFuelBtn');if(sb)sb.onclick=saveFuel10;var cb=E('clearHistoryBtn');if(cb)cb.onclick=clearAll10;
 var inp=E('aiImage');if(inp)inp.onchange=function(e){if(e.target.files&&e.target.files[0])analyze10(e.target.files[0])};
}
setTimeout(init10,150);
})();